import Head from 'next/head'
import Image from 'next/image'

import { gql } from "@apollo/client";
import client from "../apollo-client";

import styles from '../styles/Home.module.css'

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query PastLaunches {
        launchesPast(limit: 10) {
          mission_name
          launch_date_local
          launch_site {
            site_name_long
          }
          links {
            article_link
            video_link
          }
          ships {
            name
            home_port
            image
          }
        }
      }
    `,
  });
  
  return {
    props: {
      pastLaunches: data.launchesPast,
    },
 };
}

export default function Home({pastLaunches}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>witharchie test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {pastLaunches.map((launch:any) => <div key={launch.mission_name}>{launch.mission_name}</div>)}
      </main>
    </div>
  )
}
