import Head from 'next/head'
import { GetStaticProps } from 'next'
import { useEffect, useState } from 'react';
import { Input } from '@chakra-ui/react';
import client from "../apollo-client";
import InfoCard from '../components/InfoCard';
import { pastLaunches } from '../graphql/queries';
import { Launch } from '../types/Launch';
import styles from '../styles/Home.module.css'

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await client.query({
    query: pastLaunches
  });
  return {
    props: {
      pastLaunches: data.launchesPast,
    },
 };
}

type PropsType = {
  pastLaunches: Array<Launch>
}

export default function Home({ pastLaunches }: PropsType) {
  const [launches, setLaunches] = useState<Array<Launch>>(pastLaunches);
  const [searchKey, setSearchKey] = useState<string>('');
  useEffect(() => {

  }, [searchKey])
  return (
    <div className={styles.container}>
      <Head>
        <title>witharchie test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Input onChange={(e) => setSearchKey(e.target.value)}/>
        {launches.map((launch:Launch) => <InfoCard key={launch.mission_name} data={launch} />)}
      </main>
    </div>
  )
}
