/* eslint-disable react/no-children-prop */
import React from 'react';
import Head from 'next/head';
import { useCallback, useState } from 'react';
import { Box, Center, Container, Flex, Heading, Input, InputGroup, InputLeftElement, Spinner, Text } from '@chakra-ui/react';
import { SearchIcon } from '@chakra-ui/icons'
import debounce from 'lodash.debounce';

import { PAST_LAUNCHES } from '../graphql/queries';
import styles from '../styles/Home.module.css'
import { useQuery } from '@apollo/client';
import DataView from '../components/DataView';

const LIMIT_NUMBER = 60;
export default function Home() {
  const [searchKey, setSearchKey] = useState<string>('');
  const { loading, error, data } = useQuery(PAST_LAUNCHES, {
    variables: { 
      missionName: searchKey,
      limit: LIMIT_NUMBER,
      offset: 0
    },
  });

  // eslint-disable-next-line react-hooks/exhaustive-deps
  const debouncedChangeHandler = useCallback(debounce((e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchKey(e.target.value)
  }, 500),[]);

  return (
    <div className={styles.container}>
      <Head>
        <title>witharchie test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW={'full'} >
        <Heading marginY={'1rem'} size={'xl'}>Past launches by SpaceX(archie test)</Heading>
        <InputGroup width="100%" maxW="sm">
          <InputLeftElement
            pointerEvents='none'
            children={<SearchIcon color='gray.300' />}
          />
          <Input onChange={debouncedChangeHandler} placeholder="Search launchs by mission name"/>
        </InputGroup>
        {loading && (
          <Center h="12rem">
            <Spinner
              margin="auto"
              thickness="4px"
              speed="0.65s"
              emptyColor="gray.200"
              color="blue.500"
              size="xl"
            />
          </Center>)
        }
        {!loading && !error && <DataView data={data.launchesPast} />}
      </Container>
    </div>
  )
}